### PR TITLE
Added user folder on commit ecc94c7

### PR DESCRIPTION
**Pull request by ghost**
The changes are as discussed in gitter (for fewer merge conflicts), will
be refactored to same abstraction as commit ecc94c7 with better naming
perhaps

### CODE REVIEW

**Review by in42 — APPROVED** [review]
Seems ok

**Review by sagnikm95 — COMMENTED** [review]
seems fine ; in42 do yours under login

**Review by sagnikm95 — COMMENTED** [review]
ok name it auth

**Comment by ghost** [comment]
Better name it `auth`

**Pull request merged**
