### PR TITLE
Made suggested changes to backend setUp

### PR DESCRIPTION
**Pull request by sagnikm95**
Made minor changes to @devanshu0987  's code and integrated some parts of admin front-end with back-end

### CODE REVIEW

**Comment by ghost** [comment]
I thought you were just going to put the changes to @devanshu0987 code. You could have put them in some other commit.

**Comment by ghost** [comment]
Please make another pr with just that, and I will approve that.

**Comment by devanshu0987** [comment]
I think, remove the edits made to the server side. And let Vikram do that. No merge problem in future

**Comment by sagnikm95** [comment]
@devanshu0987  I thing you should see the code once; server side change is a minor one  and I have discussed with @in42  already
@tauoverpi the other changes wont affect your code; On my current dev branch i have committed these changes and reverting the changes is something I dnt want to risk [ being new to git ]. Other option being fetching the current the state to my remote and remaking the changes. I dnt see the point in that. If you do have valid reason let me know

**Comment by ghost** [comment]
Ask @in42 to review this one. I don't know much about the auth code now.

**Comment by sagnikm95** [comment]
yeah let @in42  have a look but I made no changes to the auth code though. just to my portion of the front end

**Comment by ghost** [comment]
I mean he would know about the auth integration part.

**Comment by sagnikm95** [comment]
@tauoverpi  that was there in the previous PRs

**Pull request merged**
