### PR TITLE
Add user API

### PR DESCRIPTION
**Pull request by gopalgoel19**
Added the following APIs:
GET /api/users
GET /ap/users/:username
PUT /api/users/:username
POST /api/users
DELETE /api/users/:username

### CODE REVIEW

**Comment by gopalgoel19** [comment]
@devanshu0987

**Comment by devanshu0987** [comment]
Since we have made username the primary key to find a user, we need to manually check for its uniqueness before we create a user and show the same on the frontend.

**Comment by ghost** [comment]
@devanshu0987 I would suggest you to look into passport package, because it expects a username field which it keeps unique in the database. Here is a bit of [explanation ](https://github.com/saintedlama/passport-local-mongoose#simplified-passportpassport-local-configuration) on the subject. I think this would help you in getting rid of duplicate code.

**Comment by devanshu0987** [comment]
@tauoverpi Thanks. I went through the library. What I could take out from the doc is, 

- It has static methods which abstracts serialize, deserialize as well as local strategy. Hence less code
- It has other options that we can put in to ensure uniqueness, hashing 
- Will include it in the dependencies

**Pull request closed without merging**
